// Auto-generated by scripts/apply-threejs-version.mjs
export const threeVersionInfo = {
  tag: "r180",
  npm: "0.180.0",
  baseUrl: "https://cdn.jsdelivr.net/npm/three@0.180.0/"
};

export function logThreeVersion(prefix = '[threejs-ball]') {
  const { tag, npm } = threeVersionInfo;
  // eslint-disable-next-line no-console
  console.info(`${prefix} Using Three.js ${tag} (npm ${npm})`);
}
